Repository chain-smoker/Marronnier, pull requests merged in 2023-07, with the labels that each got.

#22 [#6] MyBatis 연결 및 mapper 설정
  build.gradle
  src/main/java/com/chainsmoker/marronnier/configuration/DataBaseConfiguration.java
  src/main/java/com/chainsmoker/marronnier/member/query/application/service/MemberQService.java
  src/main/java/com/chainsmoker/marronnier/member/query/application/service/MemberQueryApplicationService.java
  src/main/java/com/chainsmoker/marronnier/member/query/infra/repository/MemberMapper.java
  src/main/java/com/chainsmoker/marronnier/member/query/infra/repository/MemberQInfraRepo.java
  src/main/resources/config/mybatis-config.xml
  src/main/resources/mapper/member/MemberMapper.xml
Labels: ✨ Feature, ⚙ Setting

#25 [#19] 맴버 엔티티 생성
  src/main/java/com/chainsmoker/marronnier/feed/query/domain/service/FeedQService.java
  src/main/java/com/chainsmoker/marronnier/member/command/domain/aggregate/entity/Member.java
  src/main/java/com/chainsmoker/marronnier/member/command/domain/repository/MemberRepository.java
  src/main/java/com/chainsmoker/marronnier/member/query/application/service/MemberService.java
  src/main/java/com/chainsmoker/marronnier/member/query/domain/entity/vo/AgeRangeVO.java
Labels: ✨ Feature

#28 [#4 , #18 , #27] 맴버 소셜 로그인 구현
  .gitignore
  build.gradle
  src/main/java/com/chainsmoker/marronnier/MarronnierApplication.java
  src/main/java/com/chainsmoker/marronnier/common/entity/BaseTimeEntity.java
  src/main/java/com/chainsmoker/marronnier/common/handler/OAuth2SuccessHandler.java
  src/main/java/com/chainsmoker/marronnier/configuration/auth/CustomOAuth2UserService.java
  src/main/java/com/chainsmoker/marronnier/configuration/auth/OAuthAttributes.java
  src/main/java/com/chainsmoker/marronnier/configuration/auth/SecurityConfiguration.java
  src/main/java/com/chainsmoker/marronnier/configuration/auth/SessionUser.java
  src/main/java/com/chainsmoker/marronnier/member/command/application/controller/MemberController.java
  src/main/java/com/chainsmoker/marronnier/member/command/domain/aggregate/entity/Member.java
  src/main/resources/static/index.html
  src/main/resources/templates/main.html
Labels: ✨ Feature

#29 [#12] 요청 엔티티 생성
  src/main/java/com/chainsmoker/marronnier/apply/command/domain/aggregate/entity/Apply.java
  src/main/java/com/chainsmoker/marronnier/apply/command/domain/aggregate/entity/ApplyEntity.java
  src/main/java/com/chainsmoker/marronnier/apply/command/domain/aggregate/entity/EnumType/CategoryEnum.java
  src/main/java/com/chainsmoker/marronnier/apply/query/application/controller/ApplyQController.java
Labels: ✨ Feature

#35 [#20] 칵테일 등록 기능
  src/main/java/com/chainsmoker/marronnier/cocktailrecipe/command/application/controller/CocktailRecipeController.java
  src/main/java/com/chainsmoker/marronnier/cocktailrecipe/command/domain/aggregate/entity/CocktailRecipe.java
  src/main/java/com/chainsmoker/marronnier/cocktailrecipe/query/domain/entity/CocktailRecipeQuery.java
  src/main/java/com/chainsmoker/marronnier/element/command/application/controller/ElementController.java
  src/main/java/com/chainsmoker/marronnier/element/command/domain/aggregate/entity/Element.java
  src/main/java/com/chainsmoker/marronnier/element/query/domain/entity/ElementQuery.java
  src/main/java/com/chainsmoker/marronnier/elementbyrecipe/command/application/controller/CocktailController.java
  src/main/java/com/chainsmoker/marronnier/elementbyrecipe/command/application/controller/ElementByRecipeController.java
  src/main/java/com/chainsmoker/marronnier/elementbyrecipe/query/domain/entity/ElementByRecipeQuery.java
  src/main/resources/templates/cocktail/cocktailrecipe/cocktailrecipe.html
  src/main/resources/templates/cocktail/element/element.html
  src/main/resources/templates/cocktail/elementbyrecipe/elementbyrecipe.html
  src/main/resources/templates/cocktail/regist.html
Labels: ✨ Feature

#39 [#30, #36, #38] MyBatis를 통한 맴버 정보 조회 기능 추가 및 JPA를 통한 맴버 생성 기능 추가
  src/main/java/com/chainsmoker/marronnier/common/entity/BaseTimeEntity.java
  src/main/java/com/chainsmoker/marronnier/configuration/DataBaseConfiguration.java
  src/main/java/com/chainsmoker/marronnier/configuration/auth/CustomOAuth2UserService.java
  src/main/java/com/chainsmoker/marronnier/configuration/auth/OAuthAttributes.java
  src/main/java/com/chainsmoker/marronnier/configuration/auth/SessionUser.java
  src/main/java/com/chainsmoker/marronnier/member/command/application/dto/CreateMemberDTO.java
  src/main/java/com/chainsmoker/marronnier/member/command/application/service/MemberCommandApplicationService.java
  src/main/java/com/chainsmoker/marronnier/member/command/application/service/MemberService.java
  src/main/java/com/chainsmoker/marronnier/member/command/domain/repository/MemberRepository.java
  src/main/java/com/chainsmoker/marronnier/member/query/application/service/MemberQueryApplicationService.java
  src/main/java/com/chainsmoker/marronnier/member/query/application/service/MemberService.java
  src/main/java/com/chainsmoker/marronnier/member/query/domain/entity/MemberQEntity.java
  src/main/java/com/chainsmoker/marronnier/member/query/domain/entity/QueryMember.java
  src/main/java/com/chainsmoker/marronnier/member/query/domain/service/MemberService.java
  src/main/java/com/chainsmoker/marronnier/member/query/infra/repository/MemberMapper.java
  src/main/resources/mapper/member/MemberMapper.xml
Labels: ✨ Feature, ⚙ Setting

#41 피드 DTO 작성 [#40] , 피드 Repository 작성[#42], query Entity 작성[#9]
  src/main/java/com/chainsmoker/marronnier/feed/command/application/dto/FeedDTO.java
  src/main/java/com/chainsmoker/marronnier/feed/command/application/service/FeedService.java
  src/main/java/com/chainsmoker/marronnier/feed/command/domain/repository/FeedReposiroty.java
  src/main/java/com/chainsmoker/marronnier/feed/query/domain/entity/FeedQEntity.java
  src/main/java/com/chainsmoker/marronnier/feed/query/domain/entity/QueryFeed.java
  src/main/java/com/chainsmoker/marronnier/feed/query/domain/repository/FeedQRepo.java
  src/main/java/com/chainsmoker/marronnier/feed/query/infra/repository/FeedMapper.java
  src/main/java/com/chainsmoker/marronnier/feed/query/infra/repository/FeedQInfraRepo.java
  src/main/resources/mapper/feed/FeedMapper.xml
Labels: ✨ Feature

#47 [Closes #45] Member 클래스 이름 수정 및 커스텀 DomainService 어노테이션 생성
  src/main/java/com/chainsmoker/marronnier/common/annotation/DomainService.java
  src/main/java/com/chainsmoker/marronnier/configuration/DataBaseConfiguration.java
  src/main/java/com/chainsmoker/marronnier/configuration/auth/CustomOAuth2UserService.java
  src/main/java/com/chainsmoker/marronnier/member/command/application/service/RegistMemberService.java
  src/main/java/com/chainsmoker/marronnier/member/query/application/service/FindMemberService.java
Labels: 🏗️ Refactoring

#48 [#46] 칵테일 등록 기능 서비스 수정
  src/main/java/com/chainsmoker/marronnier/cocktailrecipe/command/application/controller/RegistCocktailRecipeController.java
  src/main/java/com/chainsmoker/marronnier/cocktailrecipe/command/application/dto/RegistCocktailRecipeDTO.java
  src/main/java/com/chainsmoker/marronnier/cocktailrecipe/command/application/service/RegistCocktailRecipeService.java
  src/main/java/com/chainsmoker/marronnier/cocktailrecipe/command/domain/aggregate/entity/CocktailRecipeEntity.java
  src/main/java/com/chainsmoker/marronnier/cocktailrecipe/command/domain/repository/CocktailRecipeRepository.java
  src/main/java/com/chainsmoker/marronnier/cocktailrecipe/query/domain/entity/CocktailRecipeQueryEntity.java
  src/main/java/com/chainsmoker/marronnier/member/command/application/controller/MemberController.java
Labels: 🏗️ Refactoring

#52 [Closes #49, Closes #50] 술바구니 엔티티 생성 및 생성,조회, 삭제 기능 구현
  src/main/java/com/chainsmoker/marronnier/basket/command/application/controller/CreateBasketController.java
  src/main/java/com/chainsmoker/marronnier/basket/command/application/controller/DeleteBasketController.java
  src/main/java/com/chainsmoker/marronnier/basket/command/application/dto/BasketDTO.java
  src/main/java/com/chainsmoker/marronnier/basket/command/application/dto/CreateBasketDTO.java
  src/main/java/com/chainsmoker/marronnier/basket/command/application/dto/DeleteBasketDTO.java
  src/main/java/com/chainsmoker/marronnier/basket/command/application/service/DeleteBasketService.java
  src/main/java/com/chainsmoker/marronnier/basket/command/application/service/RegistBasketService.java
  src/main/java/com/chainsmoker/marronnier/basket/command/domain/aggregate/entity/Basket.java
  src/main/java/com/chainsmoker/marronnier/basket/command/domain/aggregate/vo/CockTailRecipeVO.java
  src/main/java/com/chainsmoker/marronnier/basket/command/domain/aggregate/vo/MemberVO.java
  src/main/java/com/chainsmoker/marronnier/basket/command/infra/repository/BasketRepository.java
  src/main/java/com/chainsmoker/marronnier/basket/query/application/controller/FindBasketController.java
  src/main/java/com/chainsmoker/marronnier/basket/query/application/service/FindBasketService.java
  src/main/java/com/chainsmoker/marronnier/basket/query/domain/entity/QueryBasket.java
  src/main/java/com/chainsmoker/marronnier/basket/query/domain/service/MemberRequestService.java
  src/main/java/com/chainsmoker/marronnier/basket/query/infra/repository/BasketMapper.java
  src/main/java/com/chainsmoker/marronnier/basket/query/infra/service/MemberRequestService.java
  src/main/java/com/chainsmoker/marronnier/common/annotation/InfraService.java
  src/main/java/com/chainsmoker/marronnier/member/command/application/dto/CreateMemberDTO.java
  src/main/java/com/chainsmoker/marronnier/member/query/application/dto/MemberCockTailBasketDTO.java
  src/main/java/com/chainsmoker/marronnier/member/query/application/dto/MemberQDTO.java
  src/main/java/com/chainsmoker/marronnier/member/query/infra/repository/MemberMapper.java
  src/main/resources/mapper/basket/BasketMapper.xml
  src/main/resources/templates/basket/add.html
  src/main/resources/templates/basket/memberBaskets.html
Labels: ✨ Feature

#53 [#21] 칵테일 조회 기능 및 페이지 추가
  src/main/java/com/chainsmoker/marronnier/cocktailrecipe/command/application/controller/RegistCocktailRecipeController.java
  src/main/java/com/chainsmoker/marronnier/cocktailrecipe/command/application/dto/RegistCocktailRecipeDTO.java
  src/main/java/com/chainsmoker/marronnier/cocktailrecipe/command/application/service/RegistCocktailRecipeService.java
  src/main/java/com/chainsmoker/marronnier/cocktailrecipe/command/domain/aggregate/entity/CocktailRecipe.java
  src/main/java/com/chainsmoker/marronnier/cocktailrecipe/command/domain/repository/CocktailRecipeRepository.java
  src/main/java/com/chainsmoker/marronnier/cocktailrecipe/query/application/controller/FindCocktailRecipeController.java
  src/main/java/com/chainsmoker/marronnier/cocktailrecipe/query/application/dto/FindCocktailRecipeDTO.java
  src/main/java/com/chainsmoker/marronnier/cocktailrecipe/query/application/service/FindCocktailRecipeService.java
  src/main/java/com/chainsmoker/marronnier/cocktailrecipe/query/domain/entity/CocktailRecipeQueryEntity.java
  src/main/java/com/chainsmoker/marronnier/cocktailrecipe/query/domain/entity/QueryCocktailRecipe.java
  src/main/java/com/chainsmoker/marronnier/cocktailrecipe/query/infra/repository/FindCocktailMapper.java
  src/main/java/com/chainsmoker/marronnier/element/command/application/controller/RegistElementController.java
  src/main/java/com/chainsmoker/marronnier/element/command/application/dto/RegistElementDTO.java
  src/main/java/com/chainsmoker/marronnier/element/command/domain/aggregate/entity/Element.java
  src/main/resources/mapper/cocktail/FindCocktailRecipe.xml
  src/main/resources/templates/cocktail/find/cocktailrecipe.html
  src/main/resources/templates/cocktail/findmain.html
Labels: ✨ Feature

#56 피드 DTO 수정 [#40], query Entity 수정[#9], 피드 조회기능 구현[Closes #55]
  src/main/java/com/chainsmoker/marronnier/feed/command/application/controller/FeedController.java
  src/main/java/com/chainsmoker/marronnier/feed/command/application/dto/CreateFeedDTO.java
  src/main/java/com/chainsmoker/marronnier/feed/command/application/dto/FeedDTO.java
  src/main/java/com/chainsmoker/marronnier/feed/command/application/service/FeedInsertService.java
  src/main/java/com/chainsmoker/marronnier/feed/command/domain/aggregate/VO/CocktailRecipeVO.java
  src/main/java/com/chainsmoker/marronnier/feed/command/domain/aggregate/VO/MemberVO.java
  src/main/java/com/chainsmoker/marronnier/feed/command/domain/aggregate/entity/Feed.java
  src/main/java/com/chainsmoker/marronnier/feed/command/domain/aggregate/entity/FeedEntity.java
  src/main/java/com/chainsmoker/marronnier/feed/command/domain/aggregate/vo/FeedVO.java
  src/main/java/com/chainsmoker/marronnier/feed/command/domain/service/FeedService.java
  src/main/java/com/chainsmoker/marronnier/feed/query/application/controller/QueryFeedController.java
  src/main/java/com/chainsmoker/marronnier/feed/query/application/dto/CheckFeedDTO.java
  src/main/java/com/chainsmoker/marronnier/feed/query/application/dto/FeedQDTO.java
  src/main/java/com/chainsmoker/marronnier/feed/query/application/service/FeedQService.java
  src/main/java/com/chainsmoker/marronnier/feed/query/application/service/FindFeedService.java
  src/main/java/com/chainsmoker/marronnier/feed/query/domain/entity/QueryFeed.java
  src/main/java/com/chainsmoker/marronnier/feed/query/domain/repository/FeedM.java
  src/main/java/com/chainsmoker/marronnier/feed/query/domain/service/QueryFeedService.java
  src/main/java/com/chainsmoker/marronnier/feed/query/infra/repository/FeedMapper.java
  src/main/resources/mapper/feed/FeedMapper.xml
  src/main/resources/templates/feed/detail.html
Labels: ✨ Feature, 🏗️ Refactoring

#61 [#57] Builder 어노테이션 지양 및 필요 필드에서만 Setter 사용
  src/main/java/com/chainsmoker/marronnier/cocktailrecipe/command/application/dto/RegistCocktailRecipeDTO.java
  src/main/java/com/chainsmoker/marronnier/cocktailrecipe/command/application/service/RegistCocktailRecipeService.java
  src/main/java/com/chainsmoker/marronnier/cocktailrecipe/command/domain/aggregate/entity/CocktailRecipe.java
  src/main/java/com/chainsmoker/marronnier/cocktailrecipe/query/application/dto/FindCocktailRecipeDTO.java
Labels: 🏗️ Refactoring

#63 [#57] Builder 어노테이션 제거 및 Builder 패턴 직접 구현 In MEMBER
  src/main/java/com/chainsmoker/marronnier/configuration/auth/CustomOAuth2UserService.java
  src/main/java/com/chainsmoker/marronnier/configuration/auth/SessionUser.java
  src/main/java/com/chainsmoker/marronnier/member/command/application/service/RegistMemberService.java
  src/main/java/com/chainsmoker/marronnier/member/command/domain/aggregate/entity/Member.java
Labels: 🏗️ Refactoring

#69 [#68] 비로그인 시, 로그인 페이지로 이동
  settings.gradle
  src/main/java/com/chainsmoker/marronnier/configuration/auth/CustomOAuth2UserService.java
  src/main/java/com/chainsmoker/marronnier/configuration/auth/SecurityConfiguration.java
  src/main/java/com/chainsmoker/marronnier/configuration/auth/SessionUser.java
  src/main/java/com/chainsmoker/marronnier/member/command/application/dto/CreateMemberDTO.java
  src/main/java/com/chainsmoker/marronnier/member/command/domain/aggregate/entity/EnumType/Role.java
  src/main/java/com/chainsmoker/marronnier/member/command/domain/aggregate/entity/Member.java
  src/main/java/com/chainsmoker/marronnier/member/query/domain/entity/QueryMember.java
Labels: 📬 API, 🥰 Accessibility, ✨ Feature

#66 [#34] 요청글 작성 기능 구현
  src/main/java/com/chainsmoker/marronnier/apply/command/application/controller/ApplyController.java
  src/main/java/com/chainsmoker/marronnier/apply/command/application/controller/CreateApplyController.java
  src/main/java/com/chainsmoker/marronnier/apply/command/application/dto/ApplyDTO.java
  src/main/java/com/chainsmoker/marronnier/apply/command/application/dto/CreateApplyDTO.java
  src/main/java/com/chainsmoker/marronnier/apply/command/application/service/ApplyService.java
  src/main/java/com/chainsmoker/marronnier/apply/command/application/service/RegistApplyService.java
  src/main/java/com/chainsmoker/marronnier/apply/command/domain/aggregate/entity/Apply.java
  src/main/java/com/chainsmoker/marronnier/apply/command/infra/repository/ApplyInfraRepo.java
  src/main/java/com/chainsmoker/marronnier/apply/command/infra/repository/ApplyRepository.java
  src/main/java/com/chainsmoker/marronnier/apply/query/domain/entity/ApplyQEntity.java
  src/main/resources/static/index.html
  src/main/resources/templates/apply/add.html
Labels: ✨ Feature

#71 [!hotfix] 카카오 로그인 시, 권한 설정 필드값 추가
  src/main/java/com/chainsmoker/marronnier/configuration/auth/CustomOAuth2UserService.java
  src/main/java/com/chainsmoker/marronnier/configuration/auth/SecurityConfiguration.java
  src/main/java/com/chainsmoker/marronnier/member/command/application/dto/CreateMemberDTO.java
  src/main/java/com/chainsmoker/marronnier/member/command/application/service/RegistMemberService.java
  src/main/java/com/chainsmoker/marronnier/member/command/domain/aggregate/entity/Member.java
  src/main/resources/static/images/kakao_login_medium_narrow.png
  src/main/resources/static/index.html
  src/main/resources/static/style/index.css
Labels: 🐞 BugFix

#76 [Closes #72] 어드민 엔티티 생성 및 어드민 가입 기능 구현
  src/main/java/com/chainsmoker/marronnier/admin/command/application/controller/CreateAdminController.java
  src/main/java/com/chainsmoker/marronnier/admin/command/application/controller/MainAdminController.java
  src/main/java/com/chainsmoker/marronnier/admin/command/application/dto/CreateAdminDTO.java
  src/main/java/com/chainsmoker/marronnier/admin/command/application/service/RegistAdminService.java
  src/main/java/com/chainsmoker/marronnier/admin/command/domain/aggragate/entity/Admin.java
  src/main/java/com/chainsmoker/marronnier/admin/command/domain/aggragate/entity/EnumType/Role.java
  src/main/java/com/chainsmoker/marronnier/admin/command/domain/aggragate/entity/vo/PasswordVO.java
  src/main/java/com/chainsmoker/marronnier/admin/command/domain/repository/AdminRepository.java
  src/main/java/com/chainsmoker/marronnier/configuration/auth/SecurityConfiguration.java
  src/main/resources/templates/admin/home.html
  src/main/resources/templates/admin/login.html
  src/main/resources/templates/admin/regist.html
Labels: ✨ Feature

#78 [#60, #21] 칵테일 조회 기능
  src/main/java/com/chainsmoker/marronnier/cocktailrecipe/query/application/service/FindCocktailRecipeService.java
  src/main/java/com/chainsmoker/marronnier/cocktailrecipe/query/infra/repository/FindCocktailRecipeMapper.java
  src/main/java/com/chainsmoker/marronnier/element/query/application/controller/FindElementController.java
  src/main/java/com/chainsmoker/marronnier/element/query/application/dto/FindElementDTO.java
  src/main/java/com/chainsmoker/marronnier/element/query/application/service/FindElementService.java
  src/main/java/com/chainsmoker/marronnier/element/query/infra/repository/FindElementMapper.java
  src/main/java/com/chainsmoker/marronnier/elementbyrecipe/command/domain/aggregate/entity/ElementByRecipe.java
  src/main/java/com/chainsmoker/marronnier/elementbyrecipe/query/application/controller/CocktailQController.java
  src/main/java/com/chainsmoker/marronnier/elementbyrecipe/query/application/controller/FindElementByRecipeController.java
  src/main/java/com/chainsmoker/marronnier/elementbyrecipe/query/application/dto/CocktailQDTO.java
  src/main/java/com/chainsmoker/marronnier/elementbyrecipe/query/application/dto/CocktailRecipeDTO.java
  src/main/java/com/chainsmoker/marronnier/elementbyrecipe/query/application/dto/FindElementByRecipeDTO.java
  src/main/java/com/chainsmoker/marronnier/elementbyrecipe/query/application/service/CocktailQService.java
  src/main/java/com/chainsmoker/marronnier/elementbyrecipe/query/application/service/FindElementByRecipeService.java
  src/main/java/com/chainsmoker/marronnier/elementbyrecipe/query/domain/entity/QueryElementByRecipe.java
  src/main/java/com/chainsmoker/marronnier/elementbyrecipe/query/domain/service/CocktailQService.java
  src/main/java/com/chainsmoker/marronnier/elementbyrecipe/query/domain/service/ElementRequestService.java
  src/main/java/com/chainsmoker/marronnier/elementbyrecipe/query/infra/repository/CocktailQInfraRepo.java
  src/main/java/com/chainsmoker/marronnier/elementbyrecipe/query/infra/repository/FindElementByRecipeMapper.java
  src/main/java/com/chainsmoker/marronnier/elementbyrecipe/query/infra/service/CocktailQInfraService.java
  src/main/java/com/chainsmoker/marronnier/elementbyrecipe/query/infra/service/ElementRequestService.java
  src/main/resources/mapper/cocktail/FindCocktailRecipeMapper.xml
  src/main/resources/mapper/cocktail/FindElementByRecipeMapper.xml
  src/main/resources/mapper/cocktail/FindElementMapper.xml
  src/main/resources/templates/cocktail/find/cocktailRecipe.html
  src/main/resources/templates/cocktail/find/elementByrecipe.html
Labels: ✨ Feature

#85 [Closes #60] 술바구니 칵테일 조주법 아이디를 통한 조회 구현
  src/main/java/com/chainsmoker/marronnier/basket/query/application/dto/MemberCockTailBasketDTO.java
  src/main/java/com/chainsmoker/marronnier/basket/query/application/service/FindBasketService.java
  src/main/java/com/chainsmoker/marronnier/basket/query/domain/service/CocktailRecipeRequestService.java
  src/main/java/com/chainsmoker/marronnier/basket/query/infra/service/CocktailRecipeRequestService.java
  src/main/java/com/chainsmoker/marronnier/like/command/domain/aggregate/vo/likevo.java
  src/main/resources/templates/basket/memberBaskets.html
Labels: ✨ Feature

#88 [Closes #84] Spring Security OAuth2 를 통한 소셜 로그인 사용자 정보 저장 객체 수정
  src/main/java/com/chainsmoker/marronnier/basket/command/application/controller/CreateBasketController.java
  src/main/java/com/chainsmoker/marronnier/basket/command/application/controller/DeleteBasketController.java
  src/main/java/com/chainsmoker/marronnier/basket/query/application/controller/FindBasketController.java
  src/main/java/com/chainsmoker/marronnier/common/handler/OAuth2SuccessHandler.java
  src/main/java/com/chainsmoker/marronnier/configuration/auth/CustomOAuth2UserService.java
  src/main/java/com/chainsmoker/marronnier/configuration/auth/OAuthAttributes.java
  src/main/java/com/chainsmoker/marronnier/configuration/auth/SecurityConfiguration.java
  src/main/java/com/chainsmoker/marronnier/configuration/auth/SessionUser.java
  src/main/java/com/chainsmoker/marronnier/like/command/domain/aggregate/vo/likevo.java
Labels: 🐞 BugFix, 🥰 Accessibility, 🏗️ Refactoring

#89 [#77] Member 및 Basket Repository infra 패키지에서 domain 패키지로 변경
  src/main/java/com/chainsmoker/marronnier/basket/command/application/service/DeleteBasketService.java
  src/main/java/com/chainsmoker/marronnier/basket/command/application/service/RegistBasketService.java
  src/main/java/com/chainsmoker/marronnier/basket/command/domain/repository/BasketRepository.java
  src/main/java/com/chainsmoker/marronnier/basket/query/application/service/FindBasketService.java
  src/main/java/com/chainsmoker/marronnier/basket/query/domain/repository/BasketMapper.java
  src/main/java/com/chainsmoker/marronnier/basket/query/domain/service/MemberRequestService.java
  src/main/java/com/chainsmoker/marronnier/basket/query/infra/service/MemberRequestService.java
  src/main/java/com/chainsmoker/marronnier/configuration/auth/CustomOAuth2UserService.java
  src/main/java/com/chainsmoker/marronnier/like/command/domain/aggregate/vo/LikeVO.java
  src/main/java/com/chainsmoker/marronnier/member/command/domain/repository/MemberRepository.java
  src/main/java/com/chainsmoker/marronnier/member/query/application/dto/FindMemberDTO.java
  src/main/java/com/chainsmoker/marronnier/member/query/application/service/FindMemberService.java
  src/main/java/com/chainsmoker/marronnier/member/query/domain/repository/MemberMapper.java
  src/main/resources/mapper/basket/BasketMapper.xml
  src/main/resources/mapper/member/MemberMapper.xml
Labels: 🏗️ Refactoring

#93 [Closes #92] 인증, 인가에 따른 에러 페이지 처리
  src/main/java/com/chainsmoker/marronnier/basket/query/application/service/FindBasketService.java
  src/main/java/com/chainsmoker/marronnier/basket/query/domain/service/CocktailRecipeRequest.java
  src/main/java/com/chainsmoker/marronnier/basket/query/domain/service/MemberRequest.java
  src/main/java/com/chainsmoker/marronnier/basket/query/infra/service/CocktailRecipeRequestService.java
  src/main/java/com/chainsmoker/marronnier/basket/query/infra/service/MemberRequestService.java
  src/main/java/com/chainsmoker/marronnier/configuration/auth/SecurityConfiguration.java
  src/main/java/com/chainsmoker/marronnier/main/query/application/controller/ErrorController.java
  src/main/resources/templates/main/error.html
Labels: 🥰 Accessibility, 🏗️ Refactoring

#91 [Closes #90] InfraService interface 클래스 전체 패키지 호출 수정
  src/main/java/com/chainsmoker/marronnier/basket/query/application/service/FindBasketService.java
  src/main/java/com/chainsmoker/marronnier/basket/query/domain/service/CocktailRecipeRequest.java
  src/main/java/com/chainsmoker/marronnier/basket/query/domain/service/MemberRequest.java
  src/main/java/com/chainsmoker/marronnier/basket/query/infra/service/CocktailRecipeRequestService.java
  src/main/java/com/chainsmoker/marronnier/basket/query/infra/service/MemberRequestService.java
Labels: 🏗️ Refactoring

#98 [#79] 칵테일 재료 검색 기능
  src/main/java/com/chainsmoker/marronnier/element/query/application/controller/SearchElementController.java
  src/main/java/com/chainsmoker/marronnier/element/query/application/service/SearchElementService.java
  src/main/java/com/chainsmoker/marronnier/element/query/infra/repository/SearchElementMapper.java
  src/main/resources/mapper/cocktail/SearchElementMapper.xml
  src/main/resources/templates/cocktail/searchMain.html
Labels: ✨ Feature

#99 [Closes #96] 사용자 추가 정보 업데이트 및 관련 페이지 추가 및 security redirect 수정
  src/main/java/com/chainsmoker/marronnier/common/handler/OAuth2SuccessHandler.java
  src/main/java/com/chainsmoker/marronnier/configuration/auth/CustomOAuth2UserService.java
  src/main/java/com/chainsmoker/marronnier/configuration/auth/SecurityConfiguration.java
  src/main/java/com/chainsmoker/marronnier/configuration/auth/SessionUser.java
  src/main/java/com/chainsmoker/marronnier/main/query/application/controller/MainController.java
  src/main/java/com/chainsmoker/marronnier/member/command/application/controller/MemberController.java
  src/main/java/com/chainsmoker/marronnier/member/command/application/controller/UpdateMemberController.java
  src/main/java/com/chainsmoker/marronnier/member/command/application/dto/UpdateMemberDTO.java
  src/main/java/com/chainsmoker/marronnier/member/command/application/service/UpdateMemberService.java
  src/main/java/com/chainsmoker/marronnier/member/command/domain/aggregate/entity/Member.java
  src/main/java/com/chainsmoker/marronnier/member/command/domain/repository/MemberRepo.java
  src/main/java/com/chainsmoker/marronnier/member/command/domain/repository/MemberRepository.java
  src/main/java/com/chainsmoker/marronnier/member/query/application/service/FindMemberService.java
  src/main/java/com/chainsmoker/marronnier/member/query/domain/repository/MemberMapper.java
  src/main/resources/mapper/member/MemberMapper.xml
  src/main/resources/templates/main/home.html
  src/main/resources/templates/member/additional.html
Labels: 🥰 Accessibility, ✨ Feature, 🎨 Html&css

#102 [Closes #100] 술바구니 삭제 기능 구현
  src/main/java/com/chainsmoker/marronnier/basket/command/application/controller/DeleteBasketController.java
  src/main/java/com/chainsmoker/marronnier/basket/query/application/dto/MemberCockTailBasketDTO.java
  src/main/java/com/chainsmoker/marronnier/basket/query/application/service/FindBasketService.java
  src/main/resources/templates/basket/memberBaskets.html
Labels: ✨ Feature

#104 [Closes #13] 피드 삭제 기능 [Closes #40]
  src/main/java/com/chainsmoker/marronnier/feed/command/application/controller/FeedController.java
  src/main/java/com/chainsmoker/marronnier/feed/command/application/service/FeedDeleteService.java
  src/main/java/com/chainsmoker/marronnier/feed/command/domain/service/FeedService.java
  src/main/java/com/chainsmoker/marronnier/feed/query/application/controller/QueryFeedController.java
  src/main/java/com/chainsmoker/marronnier/feed/query/application/service/FindFeedService.java
  src/main/java/com/chainsmoker/marronnier/feed/query/domain/service/QueryFeedService.java
  src/main/java/com/chainsmoker/marronnier/feed/query/infra/repository/FeedMapper.java
  src/main/resources/mapper/feed/FeedMapper.xml
  src/main/resources/templates/feed/detail.html
Labels: ✨ Feature

#105 [#87] 요청 글 삭제 기능 추가
  src/main/java/com/chainsmoker/marronnier/apply/command/application/controller/DeleteApplyController.java
  src/main/java/com/chainsmoker/marronnier/apply/command/application/service/DeleteApplyService.java
  src/main/resources/templates/apply/find.html
Labels: ✨ Feature

#103 [Closes #101] 술바구니 목록에서 피드 작성 페이지 연결
  src/main/resources/templates/basket/memberBaskets.html
Labels: ✨ Feature

#107 [#106] 동적 메인페이지 연결
  src/main/java/com/chainsmoker/marronnier/main/query/application/controller/MainController.java
  src/main/resources/static/css/main.css
  src/main/resources/static/css/noscript.css
  src/main/resources/static/images/alcohol.jpg
  src/main/resources/static/images/kakao_login_large_narrow.png
  src/main/resources/static/images/logo.png
  src/main/resources/static/js/breakpoints.min.js
  src/main/resources/static/js/browser.min.js
  src/main/resources/static/js/jquery.min.js
  src/main/resources/static/js/jquery.scrollex.min.js
  src/main/resources/static/js/jquery.scrolly.min.js
  src/main/resources/static/js/main.js
  src/main/resources/static/js/util.js
  src/main/resources/static/style/index.css
  src/main/resources/templates/apply/find.html
  src/main/resources/templates/home.html
  src/main/resources/templates/main.html
  src/main/resources/templates/main/home.html
Labels: ✨ Feature

#110 [#109] 요청 관련 컨트롤러 및 DTO 수정
  src/main/java/com/chainsmoker/marronnier/apply/command/application/controller/CreateApplyController.java
  src/main/java/com/chainsmoker/marronnier/apply/command/application/controller/DeleteApplyController.java
  src/main/java/com/chainsmoker/marronnier/apply/command/application/dto/CreateApplyDTO.java
  src/main/java/com/chainsmoker/marronnier/main/query/application/controller/MainController.java
  src/main/resources/templates/home.html
Labels: 🏗️ Refactoring

#108 [#20] Element(칵테일 재료) 등록 기능 구현
  src/main/java/com/chainsmoker/marronnier/cocktailrecipe/command/application/controller/RegistCocktailRecipeController.java
  src/main/java/com/chainsmoker/marronnier/element/command/application/controller/RegistElementController.java
  src/main/java/com/chainsmoker/marronnier/element/command/application/dto/RegistElementDTO.java
  src/main/java/com/chainsmoker/marronnier/element/command/application/service/RegistElementService.java
  src/main/java/com/chainsmoker/marronnier/element/command/domain/aggregate/EnumType/CategoryNameEnum.java
  src/main/java/com/chainsmoker/marronnier/element/command/domain/aggregate/entity/Element.java
  src/main/java/com/chainsmoker/marronnier/element/command/domain/repository/ElementRepository.java
  src/main/resources/templates/cocktail/regist/element.html
Labels: ✨ Feature

#114 [Closes #111] 404 페이지 처리
  src/main/resources/static/css/404.css
  src/main/resources/static/images/astronaut.svg
  src/main/resources/static/images/planet.svg
  src/main/resources/static/js/404.js
  src/main/resources/templates/main/error.html
Labels: 🥰 Accessibility, 🏗️ Refactoring

#113 [#112] 칵테일 관련 기능 URL 수정
  src/main/java/com/chainsmoker/marronnier/cocktailrecipe/command/application/controller/RegistCocktailRecipeController.java
  src/main/java/com/chainsmoker/marronnier/cocktailrecipe/query/application/controller/FindCocktailRecipeController.java
  src/main/java/com/chainsmoker/marronnier/element/command/application/controller/RegistElementController.java
  src/main/java/com/chainsmoker/marronnier/element/query/application/controller/FindElementController.java
  src/main/java/com/chainsmoker/marronnier/elementbyrecipe/query/application/controller/FindElementByRecipeController.java
  src/main/java/com/chainsmoker/marronnier/elementbyrecipe/query/domain/service/ElementRequest.java
  src/main/java/com/chainsmoker/marronnier/elementbyrecipe/query/infra/service/ElementRequestService.java
  src/main/resources/templates/cocktail/findMain.html
  src/main/resources/templates/cocktail/regist/cocktailRecipe.html
  src/main/resources/templates/cocktail/registMain.html
Labels: 🏗️ Refactoring

#119 [Closes #117] 맴버 카카오톡 프로필 이미지 저장
  src/main/java/com/chainsmoker/marronnier/configuration/auth/CustomOAuth2UserService.java
  src/main/java/com/chainsmoker/marronnier/configuration/auth/OAuthAttributes.java
  src/main/java/com/chainsmoker/marronnier/member/command/application/controller/UpdateMemberController.java
  src/main/java/com/chainsmoker/marronnier/member/command/application/dto/CreateMemberDTO.java
  src/main/java/com/chainsmoker/marronnier/member/command/application/dto/UpdateMemberDTO.java
  src/main/java/com/chainsmoker/marronnier/member/command/application/service/RegistMemberService.java
  src/main/java/com/chainsmoker/marronnier/member/command/application/service/UpdateMemberService.java
  src/main/java/com/chainsmoker/marronnier/member/command/domain/aggregate/entity/Member.java
Labels: 🥰 Accessibility, ✨ Feature, 🏗️ Refactoring

#121 [Closes #115] 맴버 프로필 페이지 및 템플릿 적용
  src/main/java/com/chainsmoker/marronnier/member/query/application/controller/MemberProfileController.java
  src/main/java/com/chainsmoker/marronnier/member/query/application/controller/MemberQController.java
  src/main/java/com/chainsmoker/marronnier/member/query/application/dto/FindMemberDTO.java
  src/main/java/com/chainsmoker/marronnier/member/query/application/service/FindMemberService.java
  src/main/java/com/chainsmoker/marronnier/member/query/domain/entity/QueryMember.java
  src/main/java/com/chainsmoker/marronnier/member/query/domain/service/RequestMemberBasket.java
  src/main/java/com/chainsmoker/marronnier/member/query/infra/service/MemberQInfraService.java
  src/main/java/com/chainsmoker/marronnier/member/query/infra/service/RequestMemberBasketService.java
  src/main/resources/static/css/animate.css
  src/main/resources/static/css/bootstrap.min.css
  src/main/resources/static/css/custom.css
  src/main/resources/static/css/flex-slider.css
  src/main/resources/static/css/fontawesome.css
  src/main/resources/static/css/owl.css
  src/main/resources/static/css/templatemo-cyborg-gaming.css
  src/main/resources/static/fonts/fa-brands-400.ttf
  src/main/resources/static/fonts/fa-brands-400.woff2
  src/main/resources/static/fonts/fa-regular-400.ttf
  src/main/resources/static/fonts/fa-regular-400.woff2
  src/main/resources/static/fonts/fa-solid-900.ttf
  src/main/resources/static/fonts/fa-solid-900.woff2
  src/main/resources/static/fonts/fa-v4compatibility.ttf
  src/main/resources/static/fonts/fa-v4compatibility.woff2
  src/main/resources/static/images/logo_white.png
  src/main/resources/static/js/bootstrap.min.js
  src/main/resources/static/js/custom.js
  src/main/resources/static/js/isotope.js
  src/main/resources/static/js/isotope.min.js
  src/main/resources/static/js/jquery.min.map
  src/main/resources/static/js/jquery/jquery.js
  src/main/resources/static/js/jquery/jquery.min.js
  src/main/resources/static/js/jquery/jquery.slim.js
  src/main/resources/static/js/jquery/jquery.slim.min.js
  src/main/resources/static/js/jquery/jquery.slim.min.map
  src/main/resources/static/js/owl-carousel.js
  src/main/resources/static/js/popup.js
  src/main/resources/static/js/tabs.js
  src/main/resources/templates/member/profile.html
Labels: 🥰 Accessibility, ✨ Feature, 🎨 Html&css

#120 [#118] 칵테일 추천 기능
  src/main/java/com/chainsmoker/marronnier/cocktailrecipe/query/application/controller/RecommandController.java
  src/main/java/com/chainsmoker/marronnier/cocktailrecipe/query/application/service/RecommandService.java
  src/main/java/com/chainsmoker/marronnier/cocktailrecipe/query/infra/repository/RecommandMapper.java
  src/main/resources/mapper/cocktail/RecommandMapper.xml
  src/main/resources/static/images/stream-05.jpg
  src/main/resources/templates/cocktail/question.html
  src/main/resources/templates/cocktail/recommand.html
  src/main/resources/templates/cocktail/resultCocktail.html
Labels: ✨ Feature

#125 [Closes #124] 좋아요 비동기 처리 [Closes #123] 게시글 페이지 비동기 처리
  src/main/java/com/chainsmoker/marronnier/feed/command/application/controller/FeedController.java
  src/main/java/com/chainsmoker/marronnier/feed/query/application/controller/QueryFeedController.java
  src/main/java/com/chainsmoker/marronnier/feed/query/domain/service/CheckMemberNameService.java
  src/main/java/com/chainsmoker/marronnier/feed/query/domain/service/LikeService.java
  src/main/java/com/chainsmoker/marronnier/feed/query/domain/service/QueryFeedService.java
  src/main/java/com/chainsmoker/marronnier/feed/query/infra/service/CheckMemberNameService.java
  src/main/java/com/chainsmoker/marronnier/like/command/application/controller/LikeController.java
  src/main/java/com/chainsmoker/marronnier/like/command/application/service/PushLikeService.java
  src/main/java/com/chainsmoker/marronnier/like/query/domain/entity/QueryLike.java
  src/main/resources/templates/feed/detail.html
  src/main/resources/templates/feed/feed.html
Labels: ✨ Feature, 🎨 Html&css

#127 [#126] 요청글 전체 페이지 탬플릿 적용
  src/main/java/com/chainsmoker/marronnier/apply/command/domain/aggregate/entity/Apply.java
  src/main/java/com/chainsmoker/marronnier/apply/query/application/controller/QueryApplyController.java
  src/main/java/com/chainsmoker/marronnier/apply/query/application/service/QueryApplyService.java
  src/main/java/com/chainsmoker/marronnier/apply/query/domain/entity/QueryApply.java
  src/main/java/com/chainsmoker/marronnier/configuration/auth/SecurityConfiguration.java
  src/main/resources/static/css/main.css
  src/main/resources/static/images/logo-white.png
  src/main/resources/templates/apply/detail.html
  src/main/resources/templates/apply/find.html
  src/main/resources/templates/home.html
Labels: ✨ Feature, 🎨 Html&css

#131 [#130] 어드민 홈페이지 탬플릿 적용
  src/main/java/com/chainsmoker/marronnier/configuration/auth/SecurityConfiguration.java
  src/main/resources/static/images/admin-home.jpg
  src/main/resources/templates/admin/home.html
  src/main/resources/templates/apply/find.html
Labels: 🥰 Accessibility, ✨ Feature, 🎨 Html&css

#132 [Closes #129] 사용자 인증 정보 프로필 이미지 추가
  src/main/java/com/chainsmoker/marronnier/configuration/auth/CustomOAuth2UserService.java
  src/main/java/com/chainsmoker/marronnier/configuration/auth/SessionUser.java
  src/main/resources/templates/member/additional.html
  src/main/resources/templates/member/profile.html
Labels: 🥰 Accessibility, ✨ Feature, 🎨 Html&css, 🏗️ Refactoring

#133 [#118] 칵테일 추천 기능
  src/main/java/com/chainsmoker/marronnier/cocktailrecipe/query/application/controller/RecommandController.java
  src/main/java/com/chainsmoker/marronnier/cocktailrecipe/query/application/dto/FindCocktailRecipeDTO.java
  src/main/java/com/chainsmoker/marronnier/elementbyrecipe/command/application/controller/ElementByRecipeController.java
  src/main/java/com/chainsmoker/marronnier/elementbyrecipe/command/application/controller/RegistElementByRecipeController.java
  src/main/java/com/chainsmoker/marronnier/elementbyrecipe/command/application/dto/CocktailDTO.java
  src/main/java/com/chainsmoker/marronnier/elementbyrecipe/command/application/dto/RegistElementByRecipeDTO.java
  src/main/java/com/chainsmoker/marronnier/elementbyrecipe/command/application/service/CocktailService.java
  src/main/java/com/chainsmoker/marronnier/elementbyrecipe/command/application/service/RegistElementByRecipeService.java
  src/main/java/com/chainsmoker/marronnier/elementbyrecipe/command/domain/service/CocktailService.java
  src/main/java/com/chainsmoker/marronnier/elementbyrecipe/command/infra/repository/CocktailInfraRepo.java
  src/main/java/com/chainsmoker/marronnier/elementbyrecipe/command/infra/service/CocktailInfraService.java
  src/main/java/com/chainsmoker/marronnier/elementbyrecipe/query/application/controller/FindElementByRecipeController.java
  src/main/java/com/chainsmoker/marronnier/elementbyrecipe/query/application/service/FindElementByRecipeService.java
  src/main/java/com/chainsmoker/marronnier/elementbyrecipe/query/domain/service/CocktailRecipeRequest.java
  src/main/java/com/chainsmoker/marronnier/elementbyrecipe/query/infra/service/RecipeRequestService.java
  src/main/java/com/chainsmoker/marronnier/main/query/application/controller/MainController.java
  src/main/resources/mapper/cocktail/RecommandMapper.xml
  src/main/resources/templates/cocktail/find/elementByrecipe.html
  src/main/resources/templates/cocktail/resultCocktail.html
  src/main/resources/templates/home.html
  src/test/java/com/chainsmoker/marronnier/MarronnierApplicationTests.java
Labels: ✨ Feature

#137 [Closes #136] 술바구니 ID 파라미터를 통한 추가
  build.gradle
  src/main/java/com/chainsmoker/marronnier/basket/command/application/controller/CreateBasketController.java
  src/main/java/com/chainsmoker/marronnier/basket/command/application/controller/DeleteBasketController.java
  src/main/java/com/chainsmoker/marronnier/common/handler/OAuth2SuccessHandler.java
  src/main/java/com/chainsmoker/marronnier/main/query/application/controller/MainController.java
Labels: 🏗️ Refactoring

#139 [Closes #138] 요청글 작성 페이지 템플릿 적용
  src/main/java/com/chainsmoker/marronnier/apply/command/application/controller/CreateApplyController.java
  src/main/resources/templates/apply/add.html
Labels: 🥰 Accessibility, 🎨 Html&css, 🏗️ Refactoring

#143 [Closes #140] 카카오 우편본호 입력을 통한 맴버 주소지 입력
  src/main/resources/templates/member/additional.html
  src/main/resources/templates/member/profile.html
Labels: 🥰 Accessibility, 🎨 Html&css, 🏗️ Refactoring

#135 [Closes #134] 템플릿 디자인 적용
  src/main/java/com/chainsmoker/marronnier/feed/query/application/controller/QueryFeedController.java
  src/main/java/com/chainsmoker/marronnier/feed/query/domain/service/CheckMemberNameService.java
  src/main/java/com/chainsmoker/marronnier/feed/query/domain/service/CheckMemberService.java
  src/main/java/com/chainsmoker/marronnier/feed/query/domain/service/QueryFeedService.java
  src/main/java/com/chainsmoker/marronnier/feed/query/infra/service/CheckMemberService.java
  src/main/resources/templates/feed/feed.html
  src/main/resources/templates/feed/update.html
  src/main/resources/templates/feed/write.html
Labels: ✨ Feature, 🎨 Html&css, 🏗️ Refactoring

#149 [Closes #144] 술바구니 복합키로 처리
  src/main/java/com/chainsmoker/marronnier/basket/command/application/controller/CreateBasketController.java
  src/main/java/com/chainsmoker/marronnier/basket/command/application/controller/DeleteBasketController.java
  src/main/java/com/chainsmoker/marronnier/basket/command/application/dto/DeleteBasketDTO.java
  src/main/java/com/chainsmoker/marronnier/basket/command/application/service/DeleteBasketService.java
  src/main/java/com/chainsmoker/marronnier/basket/command/application/service/RegistBasketService.java
  src/main/java/com/chainsmoker/marronnier/basket/command/domain/aggregate/entity/Basket.java
  src/main/java/com/chainsmoker/marronnier/basket/command/domain/aggregate/entity/BasketCompositeKey.java
  src/main/java/com/chainsmoker/marronnier/basket/command/domain/aggregate/vo/CockTailRecipeVO.java
  src/main/java/com/chainsmoker/marronnier/basket/command/domain/aggregate/vo/MemberVO.java
  src/main/java/com/chainsmoker/marronnier/basket/command/domain/repository/BasketRepository.java
  src/main/java/com/chainsmoker/marronnier/basket/query/application/dto/MemberCockTailBasketDTO.java
  src/main/java/com/chainsmoker/marronnier/basket/query/application/service/FindBasketService.java
  src/main/java/com/chainsmoker/marronnier/basket/query/domain/entity/QueryBasket.java
  src/main/resources/mapper/basket/BasketMapper.xml
  src/main/resources/mapper/cocktail/RecommandMapper.xml
  src/main/resources/templates/member/additional.html
  src/main/resources/templates/member/profile.html
  src/test/java/com/chainsmoker/marronnier/CompositeKeyBasketTests.java
Labels: 🐞 BugFix, ✅ Test, 🏗️ Refactoring

#152 [#151] 칵테일 조주법 recipe 컬럼추가
  src/main/java/com/chainsmoker/marronnier/cocktailrecipe/command/application/dto/RegistCocktailRecipeDTO.java
  src/main/java/com/chainsmoker/marronnier/cocktailrecipe/command/domain/aggregate/entity/CocktailRecipe.java
  src/main/java/com/chainsmoker/marronnier/cocktailrecipe/query/domain/entity/QueryCocktailRecipe.java
Labels: 🐞 BugFix

#153 [Closes #145] 사용자 정보 업데이트 옵션 처리 및 테스트 완료
  build.gradle
  src/main/java/com/chainsmoker/marronnier/member/command/application/controller/UpdateMemberController.java
  src/main/java/com/chainsmoker/marronnier/member/command/application/dto/UpdateMemberDTO.java
  src/main/resources/templates/member/additional.html
  src/test/java/com/chainsmoker/marronnier/basket/CompositeKeyBasketTests.java
  src/test/java/com/chainsmoker/marronnier/member/ProfileUpdateTests.java
Labels: 🥰 Accessibility, ✅ Test, 🎨 Html&css, 🏗️ Refactoring

#157 [Closes #156] 술바구니 정렬 기준 변경
  src/main/java/com/chainsmoker/marronnier/cocktailrecipe/command/application/service/RegistCocktailRecipeService.java
  src/main/resources/mapper/basket/BasketMapper.xml
  src/main/resources/templates/member/profile.html
Labels: 🏗️ Refactoring

#155 [Closes #154] 술바구니에서 피드 작성에 Path Variable로 칵테일 조주법 ID 전송
  src/main/java/com/chainsmoker/marronnier/cocktailrecipe/command/application/service/RegistCocktailRecipeService.java
  src/main/resources/templates/member/profile.html
Labels: 🥰 Accessibility, 🎨 Html&css, ☎️ Request

#150 [#94] 사진 업로드
  src/main/java/com/chainsmoker/marronnier/photo/command/application/controller/InsertPhotoController.java
  src/main/java/com/chainsmoker/marronnier/photo/command/application/dto/PhotoDTO.java
  src/main/java/com/chainsmoker/marronnier/photo/command/application/service/InsertPhotoService.java
  src/main/java/com/chainsmoker/marronnier/photo/command/domain/aggregate/entity/EnumType/PhotoCategory.java
  src/main/java/com/chainsmoker/marronnier/photo/command/domain/aggregate/entity/Photo.java
  src/main/java/com/chainsmoker/marronnier/photo/command/domain/aggregate/entity/PhotoCompositeKey.java
  src/main/java/com/chainsmoker/marronnier/photo/command/domain/aggregate/vo/OriginVO.java
  src/main/java/com/chainsmoker/marronnier/photo/command/domain/repository/PhotoRepository.java
  src/main/resources/templates/photo/write.html
  src/test/java/com/chainsmoker/marronnier/photo/command/application/service/InsertPhotoServiceTest.java
Labels: ✨ Feature

#159 [Closes #158] 술바구니 페이징 처리
  src/main/java/com/chainsmoker/marronnier/basket/query/application/controller/FindBasketController.java
  src/main/java/com/chainsmoker/marronnier/basket/query/application/service/FindBasketService.java
  src/main/java/com/chainsmoker/marronnier/basket/query/domain/entity/BasketCompositeKey.java
  src/main/java/com/chainsmoker/marronnier/basket/query/domain/entity/QueryBasket.java
  src/main/java/com/chainsmoker/marronnier/basket/query/domain/entity/vo/CockTailRecipeVO.java
  src/main/java/com/chainsmoker/marronnier/basket/query/domain/entity/vo/MemberVO.java
  src/main/java/com/chainsmoker/marronnier/basket/query/domain/repository/FindBasketRepository.java
  src/main/java/com/chainsmoker/marronnier/configuration/auth/CustomOAuth2UserService.java
  src/main/java/com/chainsmoker/marronnier/member/query/application/controller/MemberProfileController.java
  src/main/java/com/chainsmoker/marronnier/member/query/application/dto/FindBasketsPaginationDTO.java
  src/main/java/com/chainsmoker/marronnier/member/query/infra/service/RequestMemberBasketService.java
  src/main/resources/static/css/custom.css
  src/main/resources/templates/basket/memberBaskets.html
  src/main/resources/templates/member/profile.html
  src/test/java/com/chainsmoker/marronnier/basket/PaginationBasketTests.java
Labels: 🥰 Accessibility, ✨ Feature, 🎨 Html&css, 🏗️ Refactoring

#164 [#163] 칵테일 추천 기능 요청방식 수정
  src/main/java/com/chainsmoker/marronnier/cocktailrecipe/query/application/controller/RecommandController.java
  src/main/java/com/chainsmoker/marronnier/cocktailrecipe/query/application/service/RecommandService.java
  src/main/java/com/chainsmoker/marronnier/elementbyrecipe/query/application/controller/FindElementByRecipeController.java
  src/main/java/com/chainsmoker/marronnier/main/query/application/controller/MainController.java
  src/main/resources/templates/cocktail/find/elementByrecipe.html
  src/main/resources/templates/cocktail/question/first.html
  src/main/resources/templates/cocktail/question/second.html
  src/main/resources/templates/cocktail/question/third.html
  src/main/resources/templates/cocktail/resultCocktail.html
  src/main/resources/templates/home.html
Labels: 🥰 Accessibility, 🏗️ Refactoring

#166 [Closes #165] 관리자 로그인 회원가입 템플릿 적용
  src/main/resources/templates/admin/login.html
  src/main/resources/templates/admin/regist.html
Labels: 🥰 Accessibility, 🎨 Html&css, 🏗️ Refactoring

#169 [Closes #168] 사진 경로 설정 파일 및 외부경로 저장
  src/main/java/com/chainsmoker/marronnier/configuration/PhotoConfiguration.java
  src/main/java/com/chainsmoker/marronnier/photo/command/application/dto/PhotoDTO.java
  src/main/java/com/chainsmoker/marronnier/photo/command/application/service/InsertPhotoService.java
  src/main/java/com/chainsmoker/marronnier/photo/command/domain/aggregate/entity/Photo.java
  src/main/java/com/chainsmoker/marronnier/photo/command/domain/aggregate/entity/PhotoCompositeKey.java
  src/main/resources/templates/photo/write.html
Labels: 🥰 Accessibility, 🏗️ Refactoring

#173 [#170] 프로필페이지 프로필 이미지, navbar 프로필 이미지 리사이징
  src/main/resources/static/css/custom.css
  src/main/resources/templates/basket/memberBaskets.html
  src/main/resources/templates/member/additional.html
  src/main/resources/templates/member/profile.html
Labels: 🐞 BugFix, 🥰 Accessibility, 🎨 Html&css, 🏗️ Refactoring

#172 [Closes #171] 상세페이지 Bootstrap 적용
  src/main/resources/templates/apply/detail.html
  src/main/resources/templates/apply/find.html
Labels: ✨ Feature, 🎨 Html&css

#175 [Closes #174] 피드 작성자 프로필이 보이도록 하기
  src/main/java/com/chainsmoker/marronnier/feed/query/application/controller/QueryFeedController.java
  src/main/java/com/chainsmoker/marronnier/feed/query/application/dto/CheckFeedDTO.java
  src/main/java/com/chainsmoker/marronnier/feed/query/domain/service/QueryFeedService.java
  src/main/resources/templates/feed/feed.html
Labels: 🎨 Html&css

#181 [Closes #177] 사용자 생년월일 VO로 처리 및 예외 처리
  src/main/java/com/chainsmoker/marronnier/member/command/application/controller/UpdateMemberController.java
  src/main/java/com/chainsmoker/marronnier/member/command/application/dto/UpdateMemberDTO.java
  src/main/java/com/chainsmoker/marronnier/member/command/domain/aggregate/entity/Member.java
  src/main/java/com/chainsmoker/marronnier/member/command/domain/aggregate/vo/BirthDateVO.java
  src/main/java/com/chainsmoker/marronnier/member/command/domain/aggregate/vo/MemberVO.java
  src/main/java/com/chainsmoker/marronnier/member/command/domain/exception/BirthDateAfterException.java
  src/main/resources/mapper/member/MemberMapper.xml
  src/main/resources/templates/member/additional.html
  src/test/java/com/chainsmoker/marronnier/member/BirthDateTests.java
Labels: 🥰 Accessibility, ✅ Test, 🏗️ Refactoring

#184 [Closes #182] 사진 조회 기능 구현
  src/main/java/com/chainsmoker/marronnier/photo/query/application/controller/FindPhotoController.java
  src/main/java/com/chainsmoker/marronnier/photo/query/application/dto/FindPhotoDTO.java
  src/main/java/com/chainsmoker/marronnier/photo/query/application/service/FindPhotoService.java
  src/main/java/com/chainsmoker/marronnier/photo/query/domain/repository/PhotoMapper.java
  src/main/resources/mapper/photo/PhotoMapper.xml
  src/main/resources/templates/photo/result.html
  src/main/resources/templates/photo/write.html
  src/test/java/com/chainsmoker/marronnier/photo/command/application/service/InsertPhotoServiceTest.java
Labels: ✨ Feature

#180 [Closes #178] 피드 전체 조회 및 상세 조회시 cocktailName 출력 [Closes #179] 술바구니에서 피드 쓰기 페이지로 이동
  src/main/java/com/chainsmoker/marronnier/feed/query/application/controller/QueryFeedController.java
  src/main/java/com/chainsmoker/marronnier/feed/query/application/dto/CheckFeedDTO.java
  src/main/java/com/chainsmoker/marronnier/feed/query/domain/service/CheckCocktatilService.java
  src/main/java/com/chainsmoker/marronnier/feed/query/domain/service/QueryFeedService.java
  src/main/java/com/chainsmoker/marronnier/feed/query/infra/service/CheckCocktailService.java
  src/main/resources/templates/feed/feed.html
  src/main/resources/templates/feed/write.html
Labels: ✨ Feature, 🏗️ Refactoring

#187 [Closes #183] 관리자 같은 ID 회원가입 방지
  src/main/java/com/chainsmoker/marronnier/admin/command/application/controller/CreateAdminController.java
  src/main/java/com/chainsmoker/marronnier/admin/command/domain/aggragate/entity/Admin.java
  src/main/resources/templates/admin/regist.html
  src/test/java/com/chainsmoker/marronnier/admin/DuplicateAdminIdAndNameTests.java
Labels: 🥰 Accessibility, ✅ Test, 🎨 Html&css, 🏗️ Refactoring

#190 [Closes #95, Closes #167] 사용자의 프로필에서 좋아요 또는 작성한 피드 목록 조회
  src/main/java/com/chainsmoker/marronnier/member/query/application/controller/MemberProfileController.java
  src/main/java/com/chainsmoker/marronnier/member/query/application/service/FindMemberLikedFeedService.java
  src/main/java/com/chainsmoker/marronnier/member/query/application/service/FindMemberService.java
  src/main/java/com/chainsmoker/marronnier/member/query/application/service/FindMemberWroteFeedService.java
  src/main/java/com/chainsmoker/marronnier/member/query/domain/entity/aggregate/QueryMember.java
  src/main/java/com/chainsmoker/marronnier/member/query/domain/entity/aggregate/vo/AgeRangeVO.java
  src/main/java/com/chainsmoker/marronnier/member/query/domain/repository/MemberMapper.java
  src/main/java/com/chainsmoker/marronnier/member/query/domain/service/RequestMemberLikedFeed.java
  src/main/java/com/chainsmoker/marronnier/member/query/domain/service/RequestMemberWroteFeed.java
  src/main/java/com/chainsmoker/marronnier/member/query/infra/service/RequestMemberLikedFeedService.java
  src/main/java/com/chainsmoker/marronnier/member/query/infra/service/RequestMemberWroteFeedService.java
  src/main/resources/mapper/member/MemberMapper.xml
  src/main/resources/static/css/custom.css
  src/main/resources/templates/member/profile.html
  src/test/java/com/chainsmoker/marronnier/member/GetMemberFeedTests.java
Labels: 🥰 Accessibility, ✅ Test, ✨ Feature, 🎨 Html&css

#193 [Closes #188] 피드 작성시 사진 추가 기능 [Closes #191] 피드 전체 조회 및 상세 조회시 사진 로드 기능 [Closes #192] 사용자가 사진을 업로드 하지 않았을 때 default 사진 설정
  src/main/java/com/chainsmoker/marronnier/feed/command/application/controller/FeedController.java
  src/main/java/com/chainsmoker/marronnier/feed/command/application/service/FeedInsertService.java
  src/main/java/com/chainsmoker/marronnier/feed/command/application/service/FeedPhotoService.java
  src/main/java/com/chainsmoker/marronnier/feed/command/domain/service/InsertPhotoToFeedService.java
  src/main/java/com/chainsmoker/marronnier/feed/query/application/controller/QueryFeedController.java
  src/main/java/com/chainsmoker/marronnier/feed/query/application/dto/CheckFeedDTO.java
  src/main/java/com/chainsmoker/marronnier/feed/query/application/service/FindFeedService.java
  src/main/java/com/chainsmoker/marronnier/feed/query/domain/service/CheckPhotoService.java
  src/main/java/com/chainsmoker/marronnier/feed/query/domain/service/QueryFeedService.java
  src/main/java/com/chainsmoker/marronnier/feed/query/infra/service/CheckPhotoService.java
  src/main/java/com/chainsmoker/marronnier/feed/query/infra/service/InsertPhotoToFeedService.java
  src/main/resources/templates/feed/feed.html
  src/main/resources/templates/feed/write.html
Labels: ✨ Feature, 🎨 Html&css

#194 [!hotfix] 사용자 프로필 드롭다운 적용 안되면 문제 해결
  src/main/resources/templates/member/profile.html
Labels: 🐞 BugFix, 🥰 Accessibility, 🎨 Html&css

#198 [#191] 사용자 프로필 작성한 피드 및 좋아요한 피드 사진 적용
  src/main/resources/templates/member/profile.html
Labels: 🥰 Accessibility, 🎨 Html&css

#189 [#142] 칵테일 상세보기 페이지 조주법 추가
  src/main/java/com/chainsmoker/marronnier/cocktailrecipe/query/application/dto/FindCocktailRecipeDTO.java
  src/main/java/com/chainsmoker/marronnier/elementbyrecipe/query/application/controller/FindElementByRecipeController.java
  src/main/java/com/chainsmoker/marronnier/elementbyrecipe/query/application/dto/CocktailRecipeDTO.java
  src/main/resources/mapper/cocktail/FindCocktailRecipeMapper.xml
  src/main/resources/templates/cocktail/find/elementByrecipe.html
  src/test/java/com/chainsmoker/marronnier/cocktail/CokctailRecipeTests.java
Labels: ✨ Feature, 🎨 Html&css, 🏗️ Refactoring

#201 [Closes #200]피드를 삭제하면 좋아요도 삭제되는 기능 추가
  src/main/java/com/chainsmoker/marronnier/feed/command/application/controller/FeedController.java
  src/main/java/com/chainsmoker/marronnier/feed/command/application/service/FeedDeleteService.java
  src/main/java/com/chainsmoker/marronnier/feed/command/domain/service/DeleteLikeService.java
  src/main/java/com/chainsmoker/marronnier/feed/command/infra/service/DeleteLikeService.java
  src/main/java/com/chainsmoker/marronnier/like/command/application/service/PushLikeService.java
  src/main/java/com/chainsmoker/marronnier/like/command/domain/repository/LikeRepository.java
Labels: ✨ Feature

#204 [Closes #197]내가 작성하거나 좋아요한 피드 최신순 정렬 [Closes #202] feed table에 create…
  src/main/java/com/chainsmoker/marronnier/feed/command/application/service/FeedInsertService.java
  src/main/java/com/chainsmoker/marronnier/feed/command/domain/aggregate/entity/Feed.java
  src/main/java/com/chainsmoker/marronnier/feed/query/application/dto/CheckFeedDTO.java
  src/main/java/com/chainsmoker/marronnier/feed/query/domain/entity/QueryFeed.java
  src/main/java/com/chainsmoker/marronnier/feed/query/domain/service/QueryFeedService.java
  src/main/resources/mapper/feed/FeedMapper.xml
Labels: ✨ Feature, ☎️ Request

#206 [#199] 타임리프 공통 템플릿 적용
  src/main/resources/templates/common/modal.html
  src/main/resources/templates/feed/detail.html
  src/main/resources/templates/feed/feed.html
  src/main/resources/templates/feed/update.html
  src/main/resources/templates/feed/write.html
Labels: 🎨 Html&css

#208 [Closes #205] 이미지 생성 테스트 코드 작성
  src/test/java/com/chainsmoker/marronnier/photo/command/application/service/InsertPhotoServiceTest.java
Labels: ✅ Test

#211 [Closes #210] 신고하기 기능 구현
  src/main/java/com/chainsmoker/marronnier/apply/command/application/service/DeleteApplyService.java
  src/main/java/com/chainsmoker/marronnier/apply/command/application/service/RegistApplyService.java
  src/main/java/com/chainsmoker/marronnier/apply/command/domain/repository/ApplyRepo.java
  src/main/java/com/chainsmoker/marronnier/apply/command/domain/repository/ApplyRepository.java
  src/main/java/com/chainsmoker/marronnier/configuration/auth/SecurityConfiguration.java
  src/main/java/com/chainsmoker/marronnier/report/command/application/controller/ReportController.java
  src/main/java/com/chainsmoker/marronnier/report/command/application/controller/WriteReportController.java
  src/main/java/com/chainsmoker/marronnier/report/command/application/dto/ReportDTO.java
  src/main/java/com/chainsmoker/marronnier/report/command/application/dto/WriteReportDTO.java
  src/main/java/com/chainsmoker/marronnier/report/command/application/service/ReportService.java
  src/main/java/com/chainsmoker/marronnier/report/command/application/service/WriteReportService.java
  src/main/java/com/chainsmoker/marronnier/report/command/domain/aggregate/entity/Report.java
  src/main/java/com/chainsmoker/marronnier/report/command/domain/aggregate/entity/ReportEntity.java
  src/main/java/com/chainsmoker/marronnier/report/command/domain/repository/ReportRepo.java
  src/main/java/com/chainsmoker/marronnier/report/command/domain/repository/ReportRepository.java
  src/main/resources/templates/apply/add.html
  src/main/resources/templates/apply/detail.html
  src/main/resources/templates/report/find.html
  src/main/resources/templates/report/write.html
  src/test/java/com/chainsmoker/marronnier/photo/command/application/service/InsertPhotoServiceTest.java
Labels: ✨ Feature, 🎨 Html&css

#214 [Closes #213] 피드 신고 디자인 수정
  src/main/java/com/chainsmoker/marronnier/feed/query/application/controller/QueryFeedController.java
  src/main/resources/templates/common/modal.html
  src/main/resources/templates/feed/update.html
Labels: ✨ Feature, 🎨 Html&css

#212 [Closes #209] 칵테일 레시피 조회 테스트 코드 작성
  .github/workflows/gradle-publish.yml
  src/main/java/com/chainsmoker/marronnier/cocktailrecipe/command/application/dto/RegistCocktailRecipeDTO.java
  src/main/java/com/chainsmoker/marronnier/cocktailrecipe/command/application/service/RegistCocktailRecipeService.java
  src/main/java/com/chainsmoker/marronnier/cocktailrecipe/command/domain/aggregate/entity/CocktailRecipe.java
  src/main/java/com/chainsmoker/marronnier/cocktailrecipe/query/application/service/FindCocktailRecipeService.java
  src/main/java/com/chainsmoker/marronnier/cocktailrecipe/query/domain/entity/QueryCocktailRecipe.java
  src/main/resources/mapper/cocktail/FindCocktailRecipeMapper.xml
  src/test/java/com/chainsmoker/marronnier/cocktail/CocktailRecipeTests.java
  src/test/java/com/chainsmoker/marronnier/cocktail/CokctailRecipeTests.java
Labels: ✅ Test

#217 [Closes #215] 이미지 수정 기능 구현
  src/main/java/com/chainsmoker/marronnier/photo/command/application/controller/InsertPhotoController.java
  src/main/java/com/chainsmoker/marronnier/photo/command/application/controller/UpdatePhotoController.java
  src/main/java/com/chainsmoker/marronnier/photo/command/application/service/InsertPhotoService.java
  src/main/java/com/chainsmoker/marronnier/photo/command/application/service/UpdatePhotoService.java
  src/main/java/com/chainsmoker/marronnier/photo/command/domain/aggregate/entity/Photo.java
  src/main/java/com/chainsmoker/marronnier/photo/command/domain/repository/PhotoRepository.java
  src/test/java/com/chainsmoker/marronnier/photo/command/application/controller/InsertPhotoTest.java
  src/test/java/com/chainsmoker/marronnier/photo/command/application/controller/UpdatePhotoTest.java
  src/test/java/com/chainsmoker/marronnier/photo/command/application/service/InsertPhotoServiceTest.java
  src/test/java/com/chainsmoker/marronnier/photo/command/application/service/UpdatePhotoServiceTest.java
Labels: ✅ Test, ✨ Feature, 🏗️ Refactoring

#219 피드 사진 수정 기능 추가
  src/main/java/com/chainsmoker/marronnier/feed/command/application/controller/FeedController.java
  src/main/java/com/chainsmoker/marronnier/feed/command/application/dto/UpdateFeedDTO.java
  src/main/java/com/chainsmoker/marronnier/feed/command/application/service/FeedPhotoService.java
  src/main/java/com/chainsmoker/marronnier/feed/command/application/service/FeedUpdateService.java
  src/main/java/com/chainsmoker/marronnier/feed/command/domain/aggregate/entity/Feed.java
  src/main/java/com/chainsmoker/marronnier/feed/command/domain/service/FeedService.java
  src/main/java/com/chainsmoker/marronnier/feed/query/application/controller/QueryFeedController.java
  src/main/resources/templates/common/feed.html
  src/main/resources/templates/feed/update.html
  src/main/resources/templates/feed/write.html
Labels: ✨ Feature

#221 [Closes #216] 신고글 전체 조회(관리자)
  src/main/java/com/chainsmoker/marronnier/report/query/application/controller/QueryReportController.java
  src/main/java/com/chainsmoker/marronnier/report/query/application/controller/ReportQController.java
  src/main/java/com/chainsmoker/marronnier/report/query/application/dto/QueryReportDTO.java
  src/main/java/com/chainsmoker/marronnier/report/query/application/dto/ReportQDTO.java
  src/main/java/com/chainsmoker/marronnier/report/query/application/service/QueryReportService.java
  src/main/java/com/chainsmoker/marronnier/report/query/application/service/ReportQService.java
  src/main/java/com/chainsmoker/marronnier/report/query/domain/entity/QueryReport.java
  src/main/java/com/chainsmoker/marronnier/report/query/domain/entity/ReportQEntity.java
  src/main/java/com/chainsmoker/marronnier/report/query/domain/repository/QueryReportRepository.java
  src/main/java/com/chainsmoker/marronnier/report/query/domain/repository/ReportQRepo.java
  src/main/resources/templates/admin/home.html
  src/main/resources/templates/apply/add.html
  src/main/resources/templates/apply/detail.html
  src/main/resources/templates/apply/find.html
  src/main/resources/templates/report/find.html
Labels: ✨ Feature

#222 [Closes #220] 디자인 수정
  src/main/resources/templates/apply/add.html
  src/main/resources/templates/home.html
  src/main/resources/templates/member/additional.html
Labels: 🎨 Html&css

#224 [Closes #223] 피드 작성시 사진을 넣지 않았을 때 dafault값 처리
  src/main/java/com/chainsmoker/marronnier/feed/query/application/controller/QueryFeedController.java
  src/main/java/com/chainsmoker/marronnier/feed/query/domain/service/QueryFeedService.java
Labels: ✨ Feature

#225 [!HotFix] 테스트 사진 저장 폴더 위치 출력
  src/main/java/com/chainsmoker/marronnier/photo/command/application/service/InsertPhotoService.java
  src/test/java/com/chainsmoker/marronnier/photo/command/application/controller/UpdatePhotoTest.java
Labels: 🐞 BugFix, ✅ Test

#227 [Closes #226] 피드 테스트코드 작성
  src/test/java/com/chainsmoker/marronnier/feed/command/controller/service/FeedApplicationServiceTests.java
Labels: ✅ Test

#228 [#116] 통합 검색
  src/main/resources/templates/cocktail/find/elementByrecipe.html
  src/main/resources/templates/cocktail/question/first.html
  src/main/resources/templates/cocktail/question/second.html
  src/main/resources/templates/cocktail/question/third.html
  src/main/resources/templates/cocktail/resultCocktail.html
  src/main/resources/templates/main/search.html
Labels: 🎨 Html&css

#230 [#229] 요청글 페이지 template수정
  src/main/resources/templates/apply/add.html
Labels: 🐞 BugFix, 🎨 Html&css

#233 [Closes #232] 칵테일 추천받기 멘트 수정
  src/main/resources/templates/cocktail/question/second.html
  src/main/resources/templates/main/search.html
Labels: 🎨 Html&css

#235 [Closes #234] 카테고리 피드백 항목 추가
  src/main/java/com/chainsmoker/marronnier/apply/command/domain/aggregate/entity/EnumType/CategoryEnum.java
  src/main/resources/templates/apply/add.html
Labels: 🎨 Html&css, 🏗️ Refactoring

#236 [Closes #231] 신고 적용 시, 해당 피드 삭제
  src/main/java/com/chainsmoker/marronnier/configuration/auth/SecurityConfiguration.java
  src/main/java/com/chainsmoker/marronnier/report/command/application/controller/AcceptReportController.java
  src/main/java/com/chainsmoker/marronnier/report/command/application/controller/WriteReportController.java
  src/main/java/com/chainsmoker/marronnier/report/command/application/service/AcceptReportService.java
  src/main/java/com/chainsmoker/marronnier/report/command/domain/aggregate/entity/Report.java
  src/main/java/com/chainsmoker/marronnier/report/command/domain/service/RequestDeleteFeed.java
  src/main/java/com/chainsmoker/marronnier/report/command/infra/service/RequestDeleteFeedService.java
  src/main/resources/templates/report/find.html
  src/test/java/com/chainsmoker/marronnier/report/command/application/controller/AcceptReportControllerTest.java
Labels: 🥰 Accessibility, ✅ Test, ✨ Feature
